mysite/mysite/urls.py
from django.conf.urls import include,url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls')),
    url(r'^admin/', admin.site.urls),
]

mysite/polls/urls.py
from django.conf.urls import url

from . import views

app_name = 'polls'

urlpatterns = [
    #url(r'^$', views.IndexView.as_view(), name='index'),
    #url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    #url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    #url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),

    url(r'^post/new/$', views.post_new, name='post_new'),
    url(r'^post/(?P<pk>\d+)/detail$', views.post_detail, name='post_detail'),
    url(r'^post/(?P<pk>\d+)/edit/$', views.post_edit, name='post_edit'),
    url(r'^post/all/detail/$', views.show_detail, name='show_detail'),
    url(r'^post/(?P<pk>\d+)/q_detail/$', views.show_q_detail, name='show_q_detail'),
]

mysite/polls/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
import datetime
from django.forms import ModelForm
from django.core.exceptions import NON_FIELD_ERRORS


# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    choice_text = models.CharField(max_length=200, default="")
    votes = models.IntegerField(default=0)

    def __str__(self):
        #return self.question_text + " " + self.choice_text + " " + str(self.votes)
        return str(self.pub_date)

    def was_published_recently(self):
        return self.pub_date >= timezone.now() - timezone.timedelta(days=1)

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

def was_published_recently(self):
    now = timezone.now()
    return now - datetime.timedelta(days=1) <= self.pub_date <= now

    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'

"""
class QuestionForm(ModelForm):
    class Meta:
        model = Question
        fields = ['question_text', 'pub_date']
        error_messages = {
            NON_FIELD_ERRORS: {
                'unique_together': "%(model_name)s's %(field_labels)s are not unique.",
            }
        }
"""

mysite/polls/forms.py
from django import forms

from .models import Question, Choice

class QuestionForm(forms.ModelForm):

    class Meta:
        model = Question
        fields = ['question_text', 'pub_date', 'choice_text', 'votes']

class ChoiceForm(forms.ModelForm):

    class Meta:
        model = Choice
        fields = ['question','choice_text']

mysite/polls/views.py
from django.shortcuts import render
from django.http import HttpResponseRedirect, HttpResponse,JsonResponse
from django.http import Http404
from django.shortcuts import get_object_or_404
# Create your views here.
from django.template import loader
from django.core.urlresolvers import reverse
import datetime

from .models import Choice, Question
from django.views import generic
from django.utils import timezone
from .forms import QuestionForm, ChoiceForm
from django.shortcuts import redirect

class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        #return Question.objects.order_by('-pub_date')[:5]
        return Question.objects.filter(
            pub_date__lte=timezone.now()
        ).order_by('-pub_date')[:5]

class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def index(request):
    latest_question_list = Question.objects.order_by('-pub_date')[:5]
    #output = ', '.join([q.question_text for q in latest_question_list])
    #return HttpResponse(output)
    #----------------
    #template = loader.get_template('polls/index.html')
    context = {
        'latest_question_list' : latest_question_list,
    }
    #return HttpResponse(template.render(context, request))
    #-----------------
    #an alternate way by using render
    return render(request,'polls/index.html', context)

def detail(request, question_id):
    #return HttpResponse("You're looking at question %s." % question_id)
    """
    try:
        question = Question.objects.get(pk=question_id)
    except Question.DoesNotExist:
        raise Http404("Question does not exist")
    return render(request, 'polls/detail.html', {'question': question})
    """
    #--------------------------
    #alternate way
    question = get_object_or_404(Question, pk= question_id)
    return render(request, 'polls/detail.html', {'question': question})


def results(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})

def vote(request, question_id):
    #return HttpResponse("You're voting on question %s." % question_id)
    question = get_object_or_404(Question, pk= question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(request, 'polls/detail.html', {'question': question, 'error_message': 'you do not select a choice',})
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args = (question.id,)))

import json
def post_new(request):

    if request.method == "POST":
        form = QuestionForm(request.POST, initial={'data': json})

        # print abcd,"poppppppppppppppppppppppppppp"
        print(form)

        #form2 = ChoiceForm(request.POST)

        if form.is_valid():

            post = form.save(commit=False)
            #choice = form2.save(commit=False)
            print(type(post),"111111111111111111111111111111111111")

            post.author = request.user

            post.published_date = timezone.now()

            post.save()
            #form2.save()

            #return render(request, 'polls/post_detail.html', {'pk': post.pk})
            #return redirect('post_detail', pk=post.pk)
            #reverse('affiche_all', devise=('EURO',))

            #return HttpResponseRedirect(reverse('post_detail', args=(str(post.pk))))

            return HttpResponse(form)
    else:
        form = QuestionForm()
        #form2 = ChoiceForm()

    return render(request, 'polls/post_edit.html', {'form': form})

def post_detail(request, pk):

    question = get_object_or_404(Question, pk=pk)

    return render(request, 'polls/test.html', {'question': question})

def show_detail(request):

    #question = get_object_or_404(Question)
    question = Question.objects.all()

    return render(request, 'polls/all_detail.html', {'question': question})

def show_q_detail(request, pk):

    #question = get_object_or_404(question)

    q = Question.objects.filter(id = pk).values('question_text')

    question = Question.objects.filter(question_text = q)

    return render(request, 'polls/question_detail.html', {'question': question})

def post_edit(request, pk):
    post = get_object_or_404(Question, pk=pk)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.published_date = timezone.now()
            post.save()
            return redirect('post_detail', pk=post.pk)
    else:
        form = QuestionForm(instance=post)
    return render(request, 'polls/post_edit.html', {'form': form})

mysite/polls/templates/polls/all_detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div>

{% for q in question %}
    {{ q.id }}
    {{ q.question_text }}
    {{ q.choice_text }}
    {{ q.votes }}
    <br>
{% endfor %}

</div>
{% endblock %}

mysite/polls/templates/polls/base.html
{% load staticfiles %}
<html>
    <head>
        <title>Django blog</title>
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap.min.css">
        <link rel="stylesheet" href="//maxcdn.bootstrapcdn.com/bootstrap/3.2.0/css/bootstrap-theme.min.css">
        <link href='//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext' rel='stylesheet' type='text/css'>
        <link rel="stylesheet" href="{% static 'css/blog.css' %}">
    </head>
    <body>
        <div class="page-header">
            <a href="{% url 'polls:post_new' %}" class="top-menu"><span class="glyphicon glyphicon-plus"></span></a>
            <h1><a href="/">Django Blog</a></h1>
        </div>
        <div class="content container">
            <div class="row">
                <div class="col-md-8">
                    {% block content %}
                    {% endblock %}
                </div>
            </div>
        </div>
    </body>
</html>

mysite/polls/templates/polls/detail.html
<h1>{{ question.question_text }}</h1>

{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
{% for choice in question.choice_set.all %}
    <input type="radio" name="choice" id="choice{{ forloop.counter }}" value="{{ choice.id }}" />
    <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
{% endfor %}
<input type="submit" value="Vote" />
</form>

mysite/polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

mysite/polls/templates/polls/post_detail.html
{% extends 'polls/base.html' %}

{% block content %}
    <div class="post">
        {% if post.published_date %}
            <div class="date">
                {{ post.published_date }}
            </div>
        {% endif %}
        <a class="btn btn-default" href="{% url 'polls:post_edit' pk=question_id %}"><span class="glyphicon glyphicon-pencil"></span></a>
        <h1>{{ post.title }}</h1>
        <p>{{ post.text|linebreaksbr }}</p>
    </div>
{% endblock %}

mysite/polls/templates/polls/post_edit.html
{% extends 'polls/base.html' %}

{% block content %}
    <h1>New post</h1>
    <form method="POST" class="post-form" enctype='application/json'>{% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="save btn btn-default">Save</button>
    </form>
{% endblock %}

mysite/polls/templates/polls/post_list.html
{% extends 'blog/base.html' %}

{% block content %}
    {% for post in posts %}
        <div class="post">
            <div class="date">
                {{ post.published_date }}
            </div>
            <h1><a href="">{{ post.title }}</a></h1>
            <p>{{ post.text|linebreaksbr }}</p>
        </div>
    {% endfor %}
{% endblock content %}

mysite/polls/templates/polls/question_detail.html
{% extends 'polls/base.html' %}

{% block content %}
<div>

{% for q in question %}
    {{ q.id }}
    {{ q.question_text }}
    {{ q.choice_text }}
    {{ q.votes }}
    <br>
{% endfor %}

</div>
{% endblock %}

mysite/polls/templates/polls/results.html
h1>{{ question.question_text }}</h1>

<ul>
{% for choice in question.choice_set.all %}
    <li>{{ choice.choice_text }} -- {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
{% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

mysite/polls/templates/polls/test.html
{% extends 'polls/base.html' %}

{% block content %}
<div class="post">

    <a class="btn btn-default" href="{% url 'polls:post_edit' pk=question.id %}"><span
            class="glyphicon glyphicon-pencil"></span></a>

    <h3>Q: {{ question.question_text}}</h3>
    Date: <p>{{ question.pub_date }}</p>
    Choice: <p>{{ question.choice_text }}</p>
    Votes: <p>{{ question.votes }}</p>

</div>
{% endblock %}